#pg = 157
CFLAGS = -g
VPATH = /home/linus/Documents/c/func 
ALL = 30minprintf 33minprintf 40calc 40.1date 44minscanf 501cat 502cat 70fgets.o 76filecmp 78files

all: $(ALL)
getch.o:	getch.c
30minprintf:	30minprintf.c
33minprintf:	33minprintf.c
40calc:		40calc.c
40.1date:	40.1date.c
44minscanf:	44minscanf.c getch.o
501cat:		501cat.c
502cat:		502cat.c
70fgets.o:	70fgets.c
76filecmp:	76filecmp.c
78files:	78files.c getch.o
