#pg = 157
CFLAGS = -g
VPATH = /home/linus/Documents/c/func 
ALL = 20copyio 20getchar 30cp 31catfd 31catfp 50main

all: $(ALL)
20copyio:	20copyio.c
20getchar:	20getchar.c
30cp:		30cp.c
31catfd:	31catfd.c
31catfp:	31catfp.c
50main:		50main.c 501myfopen.c 502my_fillbuf.o
501myfopen.o:	501myfopen.c 
502my_fillbuf.o: 502my_fillbuf.c
